export const ADD_TODOS_REQUEST = "ADD_TODOS_REQUEST";
export const ADD_TODOS_SUCCESS = "ADD_TODOS_SUCCESS";
export const ADD_TODOS_FAILURE = "ADD_TODOS_FAILURE";

export const GET_TODOS_REQUEST = "GET_TODOS_REQUEST";
export const GET_TODOS_SUCCESS = "GET_TODOS_SUCCESS";
export const GET_TODOS_FAILURE = "GET_TODOS_FAILURE";

export const DEL_TODOS_REQUEST = "DEL_TODOS_REQUEST";
export const DEL_TODOS_SUCCESS = "DEL_TODOS_SUCCESS";
export const DEL_TODOS_FAILURE = "DEL_TODOS_FAILURE";

export const TOG_TODOS_REQUEST = "TOG_TODOS_REQUEST";
export const TOG_TODOS_SUCCESS = "TOG_TODOS_SUCCESS";
export const TOG_TODOS_FAILURE = "TOG_TODOS_FAILURE";
