import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";

export default function Home() {
	const router = useRouter();
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Hello World, I am Next.js</h1>

				<p className={styles.description}>Welcome to HomePage</p>

				<div className={styles.grid}>
					<a onClick={() => router.push("/about")} className={styles.card}>
						<h2>About Page &rarr;</h2>
						{/* <p>Find in-depth information about Next.js features and API.</p> */}
					</a>

					<a onClick={() => router.push("/contact-us")} className={styles.card}>
						<h2>Contact-us Page &rarr;</h2>
						{/* <p>Learn about Next.js in an interactive course with quizzes!</p> */}
					</a>
					<a onClick={() => router.push("/user")} className={styles.card}>
						<h2>User Page &rarr;</h2>
						{/* <p>Learn about Next.js in an interactive course with quizzes!</p> */}
					</a>

					{/* <a className={styles.card}>
						<h2>Examples &rarr;</h2>
						<p>Discover and deploy boilerplate example Next.js projects.</p>
					</a> */}

					{/* <a className={styles.card}>
						<h2>Deploy &rarr;</h2>
						<p>
							Instantly deploy your Next.js site to a public URL with Vercel.
						</p>
					</a> */}
				</div>
			</main>
		</div>
	);
}
