import Head from "next/head";
import { useRouter } from "next/router";
import styles from "../styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";

export default function Home() {
	const router = useRouter();
	return (
		<div className={styles.container}>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Hello World, I am Next.js</h1>
				<p className={styles.description}>Welcome to HomePage</p>

				<div className={styles.grid}>
					<a onClick={() => router.push("/about")} className={styles.card}>
						<h2>About Page &rarr;</h2>
						{/* <p>Find in-depth information about Next.js features and API.</p> */}
					</a>

					<Image width={200} height={300} src="/photo.jpg" alt="" />
					<a onClick={() => router.push("/contact-us")} className={styles.card}>
						<h2>Contact-us Page &rarr;</h2>
						{/* <p>Learn about Next.js in an interactive course with quizzes!</p> */}
					</a>
					<a onClick={() => router.push("/user")} className={styles.card}>
						<h2>User Page &rarr;</h2>
						{/* <p>Learn about Next.js in an interactive course with quizzes!</p> */}
					</a>
					<Link href="/users">
						<a>Users</a>
					</Link>
					<Link href="/posts">
						<a>Posts</a>
					</Link>
				</div>
			</main>
		</div>
	);
}
